run-01:
	pipenv run python _01_chronal_calibration.py

run-02:
	pipenv run python _02_inventory_management_system.py

run-03:
	pipenv run python _03_no_matter_how_you_slice_it.py

run-04:
	pipenv run python _04_repose_record.py

run-05:
	pipenv run python _05_alchemical_reduction.py

run-06:
	pipenv run python _06_chronal_coordinates.py

run-07:
	pipenv run python _07_the_sum_of_its_parts.py

run-08:
	pipenv run python _08_memory_maneuver.py

run-09:
	pipenv run python _09_marble_mania.py

run-10:
	pipenv run python _10_the_stars_align.py

run-11:
	pipenv run python _11_chronal_charge.py

run-12:
	pipenv run python _12_subterranean_sustainability.py

run-13:
	pipenv run python _13_mine_cart_madness.py

run-14:
	pipenv run python _14_chocolate_charts.py

run-15:
	pipenv run python _15_beverage_bandits.py

run-16:
	pipenv run python _16_chronal_classification.py

all: run-01 \
	 run-02 \
	 run-03 \
	 run-04 \
	 run-05 \
	 run-06 \
	 run-07 \
	 run-08 \
	 run-09 \
	 run-10 \
	 run-11 \
	 run-12 \
	 run-13 \
	 run-14 \
	 run-15 \
	 run-16
