run-01:
	pipenv run python 01_chronal_calibration.py

run-02:
	pipenv run python 02_inventory_management_system.py

run-03:
	pipenv run python 03_no_matter_how_you_slice_it.py

run-04:
	pipenv run python 04_repose_record.py

run-05:
	pipenv run python 05_alchemical_reduction.py

run-06:
	pipenv run python 06_chronal_coordinates.py

run-07:
	pipenv run python 07_the_sum_of_its_parts.py

run-08:
	pipenv run python 08_memory_maneuver.py

run-09:
	pipenv run python 09_marble_mania.py

run-10:
	pipenv run python 10_the_stars_align.py

run-11:
	pipenv run python 11_chronal_charge.py

run-12:
	pipenv run python 12_subterranean_sustainability.py

run-13:
	pipenv run python 13_mine_cart_madness.py