run-01:
	pipenv run python 01_chronal_calibration.py

run-02:
	pipenv run python 02_inventory_management_system.py

run-03:
	pipenv run python 03_no_matter_how_you_slice_it.py

run-04:
	pipenv run python 04_repose_record.py

run-05:
	pipenv run python 05_alchemical_reduction.py

run-06:
	pipenv run python 06_chronal_coordinates.py

run-07:
	pipenv run python 07_the_sum_of_its_parts.py
