run-01:
	pipenv run python 01_inverse_captcha.py

run-02:
	pipenv run python 02_corruption_checksum.py

run-03:
	pipenv run python 03_spiral_memory.py

run-04:
	pipenv run python 04_high_entropy_passphrases.py

run-05:
	pipenv run python 05_maze_of_twisty_trampolines.py

run-06:
	pipenv run python 06_memory_reallocation.py

run-07:
	pipenv run python 07_recursive_circus.py

run-08:
	pipenv run python 08_i_heard_you_like_registers.py

run-09:
	pipenv run python 09_stream_processing.py

run-10:
	pipenv run python 10_knot_hash.py

run-11:
	pipenv run python 11_hex_ed.py

run-12:
	pipenv run python 12_digital_plumber.py

run-13:
	pipenv run python 13_packet_scanners.py

run-14:
	pipenv run python 14_disk_defragmentation.py

run-15:
	pipenv run python 15_dueling_generators.py

run-16:
	pipenv run python 16_permutation_promenade.py

run-17:
	pipenv run python 17_spinlock.py

run-18:
	pipenv run python 18_duet.py

run-19:
	pipenv run python 19_a_series_of_tubes.py

run-20:
	pipenv run python 20_particle_swarm.py
