run-01:
	pipenv run python 01_inverse_captcha.py

run-02:
	pipenv run python 02_corruption_checksum.py

run-03:
	pipenv run python 03_spiral_memory.py

run-04:
	pipenv run python 4_high_entropy_passphrases.py
