run-01:
	pipenv run python _01_the_tyranny_of_the_rocket_equation.py

run-02:
	pipenv run python _02_1202_program_alarm.py

run-03:
	pipenv run python _03_crossed_wires.py

run-04:
	pipenv run python _04_secure_container.py

run-05:
	pipenv run python _05_sunny_with_a_chance_of_asteroids.py

run-06:
	pipenv run python _06_universal_orbit_map.py
all: run-01 \
	 run-02 \
	 run-03 \
	 run-04 \
	 run-05 \
	 run-06