run-01:
	pipenv run python _01_the_tyranny_of_the_rocket_equation.py

run-02:
	pipenv run python _02_1202_program_alarm.py

run-03:
	pipenv run python _03_crossed_wires.py

all: run-01 \
	 run-02 \
	 run-03