run-01:
	pipenv run python 01_floors.py

run-02:
	pipenv run python 02_wrapping_paper.py

run-03:
	pipenv run python 03_houses.py

run-04:
	pipenv run python 04_miner.py
	
run-05:
	pipenv run python 05_nice_strings.py

run-06:
	pipenv run python 06_lights.py

run-07:
	pipenv run python 07_wires.py

run-08:
	pipenv run python 08_strings_length.py

run-09:
	pipenv run python 09_routes.py

run-10:
	pipenv run python 10_look_and_say.py

run-11:
	pipenv run python 11_password_generator.py

run-12:
	pipenv run python 12_number_counter.py

run-13:
	pipenv run python 13_seatings.py

run-14:
	pipenv run python 14_raindeer_olympics.py

run-15:
	pipenv run python 15_ingredients.py

run-16:
	pipenv run python 16_sue.py

run-17:
	pipenv run python 17_eggnog_bottling.py

run-18:
	pipenv run python 18_lights2.py

run-19:
	pipenv run python 19_molecules.py
