run-01:
	pipenv run python 01_floors.py

run-02:
	pipenv run python 02_wrapping_paper.py

run-03:
	pipenv run python 03_houses.py

run-04:
	pipenv run python 04_miner.py
	
run-05:
	pipenv run python 05_nice_strings.py

run-06:
	pipenv run python 06_lights.py
