run-01:
	pipenv run python _01_city_navigation.py

run-02:
	pipenv run python _02_bathroom_code.py

run-03:
	pipenv run python _03_triangle.py

run-04:
	pipenv run python _04_code.py

run-05:
	pipenv run python _05_hash.py

run-06:
	pipenv run python _06_repetition_code.py

run-07:
	pipenv run python _07_ips.py

run-08:
	pipenv run python _08_display.py

run-09:
	pipenv run python _09_compression.py

run-10:
	pipenv run python _10_bots.py

run-11:
	pipenv run python _11_transporter.py

run-12:
	pipenv run python _12_assembly.py

run-13:
	pipenv run python _13_office_maze.py

run-14:
	pipenv run python _14_one_time_pad.py

run-15:
	pipenv run python _15_timing_is_everything.py

run-16:
	pipenv run python _16_dragon_checksum.py

run-17:
	pipenv run python _17_two_steps_forward.py

run-18:
	pipenv run python _18_like_a_rogue.py

run-19:
	pipenv run python _19_an_elephant_named_joseph.py

run-20:
	pipenv run python _20_firewall_rules.py

run-21:
	pipenv run python _21_scrambled_letters_and_hash.py

run-22:
	pipenv run python _22_grid_computing.py

run-23:
	pipenv run python _23_safe_cracking.py

run-24:
	pipenv run python _24_air_duct_spelunking.py

run-25:
	pipenv run python _25_clock_signal.py

all: run-01 \
	 run-02 \
     run-03 \
     run-04 \
     run-05 \
     run-06 \
     run-07 \
     run-08 \
     run-09 \
     run-10 \
     run-11 \
     run-12 \
     run-13 \
     run-14 \
     run-15 \
     run-16 \
     run-17 \
     run-18 \
     run-19 \
     run-20 \
     run-21 \
     run-22 \
     run-23 \
     run-24 \
     run-25