run-01:
	pipenv run python 01_city_navigation.py

run-02:
	pipenv run python 02_bathroom_code.py

run-03:
	pipenv run python 03_triangle.py

run-04:
	pipenv run python 04_code.py

run-05:
	pipenv run python 05_hash.py

run-06:
	pipenv run python 06_repetition_code.py

run-07:
	pipenv run python 07_ips.py

run-08:
	pipenv run python 08_display.py

run-09:
	pipenv run python 09_compression.py

run-10:
	pipenv run python 10_bots.py

run-11:
	pipenv run python 11_transporter.py

run-12:
	pipenv run python 12_assembly.py

run-13:
	pipenv run python 13_office_maze.py

run-14:
	pipenv run python 14_one_time_pad.py

run-15:
	pipenv run python 15_timing_is_everything.py

run-16:
	pipenv run python 16_dragon_checksum.py

run-17:
	pipenv run python 17_two_steps_forward.py

run-18:
	pipenv run python 18_like_a_rogue.py
